#cy.yml

name: Python Script CI

on: [push, pull_request]

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create output directory
      run: mkdir -p data/output
          
    - name: Run main script
      run: python main.py

    - name: Upload JSON output
      uses: actions/upload-artifact@v3
      with:
        name: stats-output
        path: data/output/*.json      